
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author berna
 */
public class VentanaMain extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMain
     */
    public VentanaMain(BinaryTree tree) {
        initComponents();
        this.tree = tree;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NodeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FatherTextField = new javax.swing.JTextField();
        LeftRightCheckBox = new javax.swing.JCheckBox();
        AddNodeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NselectorSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        EraseBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PreordenTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elemento del nodo");

        jLabel2.setText("Padre del nodo");

        FatherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherTextFieldActionPerformed(evt);
            }
        });

        LeftRightCheckBox.setText("Hijo Izquierdo?");
        LeftRightCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftRightCheckBoxActionPerformed(evt);
            }
        });

        AddNodeButton.setText("Agregar Nodo");
        AddNodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNodeButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Recorrido del arbol actual siguiendo el Pre orden");

        jLabel4.setText("En caso de dejar vacio es un hijo derecho");

        NselectorSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel5.setText("Nivel \"n\" para eliminar");

        EraseBtn.setText("Eliminar por nivel");
        EraseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(PreordenTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(NodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(FatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(LeftRightCheckBox)
                                .addGap(60, 60, 60)
                                .addComponent(AddNodeButton))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(NselectorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(EraseBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LeftRightCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddNodeButton)
                        .addGap(15, 15, 15)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NselectorSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EraseBtn))
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeftRightCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftRightCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeftRightCheckBoxActionPerformed

    private void FatherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherTextFieldActionPerformed

    private void AddNodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNodeButtonActionPerformed
        int node = 0;
        int father = 0;
        
    try {
        node = Integer.parseInt(NodeTextField.getText());
        if (!tree.emptyTree()){
        father = Integer.parseInt(FatherTextField.getText());
        }
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Los nodos para ser referidos tienen que ser numeros enteros");
        }
        int operationStatus;
        operationStatus = tree.insertBTNode(node, father, LeftRightCheckBox.isSelected(), tree.getRoot());
        switch (operationStatus) {
            case 1:
                tree.setTreepath("R");
                tree.printPreOrden(tree.getRoot());
                PreordenTextPane.setText(tree.getTreepath());
                System.out.println(tree.getTreepath());
                JOptionPane.showMessageDialog(this, "Agregado con Exito!");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "El padre ya tiene un hijo de ese lado");
                break;
            default:
                JOptionPane.showMessageDialog(this, "No existe ese padre");
                break;
        }
        
    }//GEN-LAST:event_AddNodeButtonActionPerformed

    private void EraseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseBtnActionPerformed
        int n = (Integer)NselectorSpinner.getValue();
        tree.borrarNivel(tree.getRoot(), n);
        System.out.println(tree.getTreepath());
        tree.setTreepath("R");
        System.out.println(tree.getTreepath());
        tree.printPreOrden(tree.getRoot());
        PreordenTextPane.setText(tree.getTreepath());
        System.out.println(tree.getTreepath());
    }//GEN-LAST:event_EraseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaMain().setVisible(true);
//            }
//        });
//    }
    BinaryTree tree;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNodeButton;
    private javax.swing.JButton EraseBtn;
    private javax.swing.JTextField FatherTextField;
    private javax.swing.JCheckBox LeftRightCheckBox;
    private javax.swing.JTextField NodeTextField;
    private javax.swing.JSpinner NselectorSpinner;
    private javax.swing.JTextPane PreordenTextPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
